"""baseline schema after phase 5

A single snapshot rather than six migrations mirroring the real history.

The six schema changes (graph_projected, delegations, agent_identities +
a2a_decisions, nullable identity timestamps, incidents + incident_events) were
never released: no database has ever existed in an intermediate state, and none
ever will. An incremental history would describe a sequence of upgrades nobody
has performed or can perform — five hand-written steps whose only verifiable
property is their endpoint, offered for narrative value. The real sequence, with
the reasoning behind each change, is in the git history where it belongs.

Verified against a database built by the previous create_all path: identical
across all 109 columns, constraints and indexes, with a clean pg_dump diff, and
alembic autogenerate finds nothing further to do.

Revision ID: e4913d78cd73
Revises:
Create Date: 2026-09-09 20:40:10.823553
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "e4913d78cd73"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("target_type", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.String(length=255), nullable=False),
        sa.Column("action_type", sa.String(length=32), nullable=False),
        sa.Column(
            "permissions_used",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("reported_status", sa.String(length=16), nullable=False),
        sa.Column("platform_status", sa.String(length=16), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "graph_projected",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "actor_suspended",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("parent_event_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_event_id"], ["agent_events.event_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "ix_agent_events_actor_id", "agent_events", ["actor_id"], unique=False
    )
    op.create_index(
        "ix_agent_events_actor_suspended",
        "agent_events",
        ["actor_suspended"],
        unique=False,
        postgresql_where=sa.text("actor_suspended = true"),
    )
    op.create_index(
        "ix_agent_events_actor_timestamp",
        "agent_events",
        ["actor_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_agent_events_parent_event_id",
        "agent_events",
        ["parent_event_id"],
        unique=False,
    )
    op.create_index(
        "ix_agent_events_platform_status",
        "agent_events",
        ["platform_status"],
        unique=False,
    )
    op.create_index(
        "ix_agent_events_reported_status",
        "agent_events",
        ["reported_status"],
        unique=False,
    )
    op.create_index(
        "ix_agent_events_target_id", "agent_events", ["target_id"], unique=False
    )
    op.create_index(
        "ix_agent_events_timestamp", "agent_events", ["timestamp"], unique=False
    )
    op.create_index(
        "ix_agent_events_unprojected",
        "agent_events",
        ["graph_projected"],
        unique=False,
        postgresql_where=sa.text("graph_projected = false"),
    )
    op.create_table(
        "agent_identities",
        sa.Column("agent_id", sa.String(length=255), nullable=False),
        sa.Column(
            "trust_level",
            sa.String(length=32),
            server_default=sa.text("'unrated'"),
            nullable=False,
        ),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("agent_id"),
    )
    op.create_index(
        "ix_agent_identities_trust_level",
        "agent_identities",
        ["trust_level"],
        unique=False,
    )
    op.create_table(
        "incidents",
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'open'"),
            nullable=False,
        ),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column(
            "trigger_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=255), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("incident_id"),
    )
    op.create_index("ix_incidents_agent_id", "incidents", ["agent_id"], unique=False)
    op.create_index("ix_incidents_opened_at", "incidents", ["opened_at"], unique=False)
    op.create_index("ix_incidents_status", "incidents", ["status"], unique=False)
    op.create_index(
        "ux_incidents_one_active_per_agent",
        "incidents",
        ["agent_id"],
        unique=True,
        postgresql_where=sa.text("status <> 'resolved'"),
    )
    op.create_table(
        "a2a_decisions",
        sa.Column("decision_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("requester_id", sa.String(length=255), nullable=False),
        sa.Column("target_id", sa.String(length=255), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("rule", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "requester_trust",
            sa.String(length=32),
            server_default=sa.text("'unrated'"),
            nullable=False,
        ),
        sa.Column(
            "target_trust",
            sa.String(length=32),
            server_default=sa.text("'unrated'"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["agent_events.event_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("decision_id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_index(
        "ix_a2a_decisions_decided_at", "a2a_decisions", ["decided_at"], unique=False
    )
    op.create_index(
        "ix_a2a_decisions_decision", "a2a_decisions", ["decision"], unique=False
    )
    op.create_index(
        "ix_a2a_decisions_requester_id", "a2a_decisions", ["requester_id"], unique=False
    )
    op.create_index(
        "ix_a2a_decisions_target_id", "a2a_decisions", ["target_id"], unique=False
    )
    op.create_table(
        "alerts",
        sa.Column("alert_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("rule_name", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["agent_events.event_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("alert_id"),
    )
    op.create_index("ix_alerts_event_id", "alerts", ["event_id"], unique=False)
    op.create_index("ix_alerts_rule_name", "alerts", ["rule_name"], unique=False)
    op.create_index("ix_alerts_triggered_at", "alerts", ["triggered_at"], unique=False)
    op.create_table(
        "delegations",
        sa.Column("delegation_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("delegator_id", sa.String(length=255), nullable=False),
        sa.Column("delegate_id", sa.String(length=255), nullable=False),
        sa.Column(
            "requested_permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "granted_permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "permission_decisions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), server_default="", nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["agent_events.event_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("delegation_id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_index(
        "ix_delegations_decided_at", "delegations", ["decided_at"], unique=False
    )
    op.create_index(
        "ix_delegations_decision", "delegations", ["decision"], unique=False
    )
    op.create_index(
        "ix_delegations_delegate_id", "delegations", ["delegate_id"], unique=False
    )
    op.create_index(
        "ix_delegations_delegator_id", "delegations", ["delegator_id"], unique=False
    )
    op.create_table(
        "incident_events",
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("layer", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.Text(), server_default="", nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["agent_events.event_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["incidents.incident_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("incident_id", "event_id", "layer"),
    )
    op.create_index(
        "ix_incident_events_event_id", "incident_events", ["event_id"], unique=False
    )
    op.create_index(
        "ix_incident_events_layer", "incident_events", ["layer"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_incident_events_layer", table_name="incident_events")
    op.drop_index("ix_incident_events_event_id", table_name="incident_events")
    op.drop_table("incident_events")
    op.drop_index("ix_delegations_delegator_id", table_name="delegations")
    op.drop_index("ix_delegations_delegate_id", table_name="delegations")
    op.drop_index("ix_delegations_decision", table_name="delegations")
    op.drop_index("ix_delegations_decided_at", table_name="delegations")
    op.drop_table("delegations")
    op.drop_index("ix_alerts_triggered_at", table_name="alerts")
    op.drop_index("ix_alerts_rule_name", table_name="alerts")
    op.drop_index("ix_alerts_event_id", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index("ix_a2a_decisions_target_id", table_name="a2a_decisions")
    op.drop_index("ix_a2a_decisions_requester_id", table_name="a2a_decisions")
    op.drop_index("ix_a2a_decisions_decision", table_name="a2a_decisions")
    op.drop_index("ix_a2a_decisions_decided_at", table_name="a2a_decisions")
    op.drop_table("a2a_decisions")
    op.drop_index(
        "ux_incidents_one_active_per_agent",
        table_name="incidents",
        postgresql_where=sa.text("status <> 'resolved'"),
    )
    op.drop_index("ix_incidents_status", table_name="incidents")
    op.drop_index("ix_incidents_opened_at", table_name="incidents")
    op.drop_index("ix_incidents_agent_id", table_name="incidents")
    op.drop_table("incidents")
    op.drop_index("ix_agent_identities_trust_level", table_name="agent_identities")
    op.drop_table("agent_identities")
    op.drop_index(
        "ix_agent_events_unprojected",
        table_name="agent_events",
        postgresql_where=sa.text("graph_projected = false"),
    )
    op.drop_index("ix_agent_events_timestamp", table_name="agent_events")
    op.drop_index("ix_agent_events_target_id", table_name="agent_events")
    op.drop_index("ix_agent_events_reported_status", table_name="agent_events")
    op.drop_index("ix_agent_events_platform_status", table_name="agent_events")
    op.drop_index("ix_agent_events_parent_event_id", table_name="agent_events")
    op.drop_index("ix_agent_events_actor_timestamp", table_name="agent_events")
    op.drop_index(
        "ix_agent_events_actor_suspended",
        table_name="agent_events",
        postgresql_where=sa.text("actor_suspended = true"),
    )
    op.drop_index("ix_agent_events_actor_id", table_name="agent_events")
    op.drop_table("agent_events")
    # ### end Alembic commands ###
